// AUTO-GENERATED by scripts/set-env.js — do not edit manually.
export const environment = {
  production: false,
  supabaseUrl: 'https://ujppjsblwfmwlmucxmet.supabase.co',
  supabaseAnonKey: 'sb_publishable_v4TQ0TtQxLxAgDMZekK_iQ_vVqEbINb',
};
