// AUTO-GENERATED by scripts/set-env.js — do not edit manually.
export const environment = {
  production: true,
  supabaseUrl: 'https://ujppjsblwfmwlmucxmet.supabase.co',
  supabaseAnonKey: 'sb_publishable_v4TQ0TtQxLxAgDMZekK_iQ_vVqEbINb',
  gaMeasurementId: 'G-7S7MR1JGNT',
};
