// Writes Supabase credentials into Angular environment files so they are
// baked into the bundle at compile time.
//
// Both environment.ts and environment.prod.ts are always written (and both
// are gitignored — see .gitignore) because Angular's build-time
// `fileReplacements` (environment.ts → environment.prod.ts in production)
// still requires environment.ts to physically exist for module resolution,
// even though its contents get swapped out for prod builds.
//
// Usage:
//   node scripts/set-env.js          → both files, production: true  (Netlify CI)
//   node scripts/set-env.js --dev    → both files, production: false (local dev)
const { writeFileSync, mkdirSync, readFileSync, existsSync } = require('fs');
const { resolve } = require('path');

const isDev = process.argv.includes('--dev');

// In dev mode, load .env.local ourselves (netlify dev may not have run yet)
if (isDev) {
  const envPath = resolve(__dirname, '../.env.local');
  if (existsSync(envPath)) {
    const lines = readFileSync(envPath, 'utf8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      if (key && !process.env[key]) process.env[key] = val;
    }
    console.log('[set-env] Loaded .env.local');
  } else {
    console.warn('[set-env] .env.local not found — create it from .env.example');
  }
}

const supabaseUrl     = process.env.NEXT_PUBLIC_SUPABASE_URL     || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
const gaMeasurementId = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('[set-env] WARNING: Supabase env vars are missing — auth will not work on this deploy.');
}

if (!gaMeasurementId) {
  console.warn('[set-env] WARNING: NEXT_PUBLIC_GA_MEASUREMENT_ID is missing — Google Analytics will not load.');
}

const buildEnvironmentFile = (production) => `// AUTO-GENERATED by scripts/set-env.js — do not edit manually.
export const environment = {
  production: ${production},
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
  gaMeasurementId: '${gaMeasurementId}',
};
`;

const dir = resolve(__dirname, '../src/app/environments');
mkdirSync(dir, { recursive: true });

// environment.ts always mirrors the current run's values (dev: false in
// Netlify CI where it's never actually loaded by the build, since
// fileReplacements swaps in environment.prod.ts's content instead).
writeFileSync(resolve(dir, 'environment.ts'), buildEnvironmentFile(isDev ? 'false' : 'true'));
writeFileSync(resolve(dir, 'environment.prod.ts'), buildEnvironmentFile(true));
console.log('[set-env] environment.ts and environment.prod.ts written successfully.');
