// Writes Supabase credentials into an Angular environment file so they are
// baked into the bundle at compile time.
//
// Usage:
//   node scripts/set-env.js          → writes environment.prod.ts  (Netlify CI)
//   node scripts/set-env.js --dev    → writes environment.ts       (local dev)
const { writeFileSync, mkdirSync, readFileSync, existsSync } = require('fs');
const { resolve } = require('path');

const isDev = process.argv.includes('--dev');

// In dev mode, load .env.local ourselves (netlify dev may not have run yet)
if (isDev) {
  const envPath = resolve(__dirname, '../.env.local');
  if (existsSync(envPath)) {
    const lines = readFileSync(envPath, 'utf8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      if (key && !process.env[key]) process.env[key] = val;
    }
    console.log('[set-env] Loaded .env.local');
  } else {
    console.warn('[set-env] .env.local not found — create it from .env.example');
  }
}

const supabaseUrl     = process.env.NEXT_PUBLIC_SUPABASE_URL     || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('[set-env] WARNING: Supabase env vars are missing — auth will not work on this deploy.');
}

const content = `// AUTO-GENERATED by scripts/set-env.js — do not edit manually.
export const environment = {
  production: ${isDev ? 'false' : 'true'},
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
};
`;

const dir = resolve(__dirname, '../src/app/environments');
mkdirSync(dir, { recursive: true });

const outFile = isDev ? 'environment.ts' : 'environment.prod.ts';
writeFileSync(resolve(dir, outFile), content);
console.log(`[set-env] ${outFile} written successfully.`);
