// Runs before `npm run build` on Netlify.
// Reads real credentials from Netlify environment variables and writes
// them into environment.prod.ts so the Angular production bundle has them
// baked in at compile time.
const { writeFileSync, mkdirSync } = require('fs');
const { resolve } = require('path');

const supabaseUrl     = process.env.NEXT_PUBLIC_SUPABASE_URL     || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('[set-env] WARNING: Supabase env vars are missing — auth will not work on this deploy.');
}

const content = `// AUTO-GENERATED by scripts/set-env.js — do not edit manually.
export const environment = {
  production: true,
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
};
`;

const dir = resolve(__dirname, '../src/app/environments');
mkdirSync(dir, { recursive: true });
writeFileSync(resolve(dir, 'environment.prod.ts'), content);
console.log('[set-env] environment.prod.ts written successfully.');
